### ISSUE TITLE
about collected data

### ISSUE THREAD

**Issue by Xiang-Liu** [hirakujira/CPU-Identifier#3]
hi hirakujira, as well as i am concerned, you have collected data about A9 chip manufacturer in the A9 identification app. I am extremely hope to get an silver 6s plus 128g with a Samsung processor. Recently I have purchased more than 10 silver 6s plus 128 Gigabytes. However,  none of them contains the Samsung processor. From the data you collected, is there any Silver 6s Plus 128 Gigabytes contains the Samsung processor? If there was, where did those phones appears? Hong Kong? Mainland China or the USA? I am very appreciate your help.

**Comment by hirakujira** [comment]
Currently, I only find about 10 records about that spec. Most of them are in the U.S. only 2 of them from China, 2 of them from HongKong. However the sample is not enough, I think we can't get any conclusion from this data.

**Comment by Xiang-Liu** [comment]
Thanks a lots, although the sample is far from enough to get any conclusion, but this information still helps a lot. At least this means I still have a chance to get the spec which i dreamed. Currently i am in Hong Kong, I will try to make more purchase in these days.......I am wondering the current ratio of samsung 6sp 128 silver to all 6sp 128 silver inside Hong Kong.

**Comment by hirakujira** [comment]
If you can't read Chinese, I will translate to English:

為什麼你要買三星版的呢？一般統計不是台積電版的比較省電？

另外好奇你是退貨重買還是直接買了10隻，因為或許退貨重買的分佈跟全新品不同
最後，提醒一下，你那個款式三星只有大概10%的機會中獎，有點難

**Comment by Xiang-Liu** [comment]
出於個人原因想搞個14nm的來玩。今天看到統計的數據中128plus多了很多三星的，請問多數增量是出現在香港嗎？另外我是買了退，退了再買⋯

**Comment by hirakujira** [comment]
台灣今天開賣了，然後台灣一堆三星(plus 約 90%)，所以哀嚎中

**Comment by Xiang-Liu** [comment]
我看見你把台灣版本的各容量分布圖做了出來。很期待香港版本也出這個統計功能～
