### ISSUE TITLE
用其他手機測會找不到圖

### ISSUE THREAD

**Issue by Hokila** [hirakujira/CPU-Identifier#5]
line 92
 if(imageName ) {
     //add imageView，但是沒有A9以外的圖
}

是否改成
 if(imageName &&isA9) {

這樣其他舊款手機就不會出現空的imageView

**Comment by hirakujira** [comment]
有啊，61~78 行就是給其他手機測的

**Comment by Hokila** [comment]
我看錯了，原來圖是放在resource folder裡，沒有在Assets.xcassets裡

我把這關掉
